In [1]:
import tensorflow as tf
import numpy as np


In [2]:
b=np.ones([3,3])
b=tf.convert_to_tensor(b,dtype=tf.float32) # numpy to tensor
print(b)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [7]:
c=tf.zeros([2,3,2,1])
print(c)
d=c[1,1]
e=c[1,:]
print(e)

tf.Tensor(
[[[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]], shape=(2, 3, 2, 1), dtype=float32)
tf.Tensor(
[[[0.]
  [0.]]

 [[0.]
  [0.]]

 [[0.]
  [0.]]], shape=(3, 2, 1), dtype=float32)
